# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Eric Barbour
tagline:             ''
description:         'Whatever comes to mind'
url: 				 http://barbour-em.github.io
baseurl: 			 ""
paginate:            5


# About/contact
author:
  name:              Eric Barbour
  url:               https://twitter.com/ebarbour22
  email:             emb4gu@virginia.edu

# Custom vars
version:             1.0.0
