# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Eric Barbour
tagline:             '(or emacs dev)'
description:         'Bloggings about Emacs and software/web development. I generally talk about Linux, elisp, python, and javascript'
url:                 http://barbour-em.github.io
baseurl:             ""
paginate:            4


# About/contact
author:
  name:              Eric Barbour
  url:               https://twitter.com/ebarbour22
  email:             emb4gu@virginia.edu

# Custom vars
version:             1.1.0
