baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "(or emacs dev linux)"
copyright = "Copyright (c) 2016, Eric Barbour; all rights reserved."
canonifyurls = true
paginate = 6

[Params]
  Author = "Eric Barbour"
  disqusShortname = "ebfender22lmao"
